type_name:
  allowed_symbols: "_"
disabled_rules:
  - type_body_length
  - trailing_comma
identifier_name:
  min_length: 2
  excluded:
    - i
    - x
    - y
    - id
  allowed_symbols: "_"
excluded:
  - .build
line_length:
  warning: 200
  error: 250
