name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v1

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: generate xcode project for xcodebuild
      run: swift package generate-xcodeproj

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: Homebrew build helpers install
      run: |
        brew install swiftlint
        brew install swiftformat

    - name: build and test
      run: swift test -v

    - name: swiftlint
      run: swiftlint

