name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout Project
      uses: actions/checkout@v2

    - name: Switch to Xcode 11
      run: sudo xcode-select -s /Applications/Xcode_11.app

    - name: generate xcode project for xcodebuild
      run: swift package generate-xcodeproj

    - name: Show Build Version
      run: xcodebuild -version

    - name: Show Build Settings
      run: xcodebuild -showBuildSettings

    - name: Show Build SDK
      run: xcodebuild -showsdks

    - name: Homebrew build helpers install
      run: |
        brew install swiftlint
        brew install swiftformat

    - name: build and test
      run: swift test --enable-code-coverage -v

    - name: env review
      run: env

    - name: Prepare Code Coverage
      run: xcrun llvm-cov export -format="lcov" .build/debug/SwiftVizPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - name: Upload to CodeCov.io
      run: bash <(curl https://codecov.io/bash)
      env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    - name: swiftlint
      run: swiftlint

